[colors.primary]
foreground = "#c9d1d9"
background = "#010409"

[colors.cursor]
text = "#010409"
cursor = "#c9d1d9"

[colors.selection]
text = "#c9d1d9"
background = "#264f78"

[colors.normal]
black = "#484f58"
red = "#ec8e2c"
green = "#58a6ff"
yellow = "#d29922"
blue = "#58a6ff"
magenta = "#bc8cff"
cyan = "#39c5cf"
white = "#b1bac4"

[colors.bright]
black = "#6e7681"
red = "#fdac54"
green = "#79c0ff"
yellow = "#e3b341"
blue = "#79c0ff"
magenta = "#d2a8ff"
cyan = "#56d4dd"
white = "#ffffff"
